### ISSUE TITLE
2nd Level

### ISSUE THREAD

**Issue by brosius02** [HotsauceFiretruck/A-Western-Story#176]
After fighting the way through on the second level when the sheriff appears it is confusing and does not make sense on how to fight him. He was stuck on a roof and I shot bullets but nothing happened. And the main character did not appear.

**Comment by tranqnhan** [comment]
screen shot please

**Comment by tranqnhan** [comment]
i know exactly what the problem is

**Comment by CodingSyntax** [comment]
was depth issue, now is fix. Yay
