### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by ethan-id** [HotsauceFiretruck/A-Western-Story#180]
Tried to put it into its own scene, but so far it the game pauses succesfully (minimal testing), but I can't figure out how to unpause it. I'm sure it's simple, but my brain is also simple so I can't figure it out. help
![image](https://user-images.githubusercontent.com/34170237/69117977-49835e00-0a57-11ea-9114-96c8bf001d0e.png)
This is the pause button, the section that 'works', but could be improved.
This would be placed in each level or file that needs a pause button/return to menu option.
![image](https://user-images.githubusercontent.com/34170237/69118014-7b94c000-0a57-11ea-9874-50b483a8fd2c.png)
These lines specifically always cause errors. No matter what function of a scene I tried to use, it says it does not exist in the console. I believe that I've created the file correctly and added it to storymode.js with the correct key and everything, but I may be wrong.
If someone else could figure it out it would be appreciated.

**Comment by tranqnhan** [comment]
use this.scene.pause("scene_key")

**Comment by ethan-id** [comment]
fixed function error; using this.scene.switch('scene_key');
fixed bug
