### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by Lui798** [HotsauceFiretruck/A-Western-Story#191]
There is an issue on mobile and small screens where buttons are not positioned properly and can go off the screen. Can be seen if you launch the arena menu in a small window. Does this have something to do with removing the scaling stuff?

**Comment by tranqnhan** [comment]
Yes, remove all references to scale in the arena mode, arena preloader, and arena death scene

**Comment by Lui798** [comment]
Fixed by ea21185ba440e78f578776289e98959f14267aec
