### ISSUE TITLE
Bug with powerups/something related.

### ISSUE THREAD

**Issue by ethan-id** [HotsauceFiretruck/A-Western-Story#240]
When a scene is switched or a change to a new tilemap happens, if there is an untouched powerup still on the ground. There is an error.

This bug can be recreated by playing level 4 till the church part, then answer 'yes' when prompted by the priests. The game will tell you there is a powerup to pick up, but if you ignore it, there is an error that crashes the game.

Help is appreciated.

Error- 
![image](https://user-images.githubusercontent.com/34170237/69841738-0c248a80-1226-11ea-815a-eafa40099fe6.png)

**Comment by tranqnhan** [comment]
Solve I got the removal order wrong. big dumb
