### ISSUE TITLE
Enter Username does not work in FullScreen Mode

### ISSUE THREAD

**Issue by tranqnhan** [HotsauceFiretruck/A-Western-Story#255]
It does not appear in fullscreen mode
Menu->FullScreen->Arena

**Comment by Lui798** [comment]
Did some quick research, and im not 100% sure if this can be fixed as the browser disables keyboard input in fullscreen. Might be able to hack around it, ill have to see

**Comment by Lui798** [comment]
Wait I see the issue now the whole text box doesn't appear. We do fullscreen in phaser so this is an issue with phaser not displaying html elements while fullscreen. This most likely cannot be fixed unless we don't use phaser's fullscreen.

**Comment by mtliendo** [comment]
I haven't ran the code locally, so I apologize in advance if this is off base, but by looking at the source code, would it by chance be that you have styles conflicting? 

By default the input box [is set to `display:none`](https://github.com/HotsauceFiretruck/A-Western-Story/blob/31cd3380e88da8be01320014c45eb68a201570fc/index.html#L47) 

edit: 
Another place to look into would be [here as well](https://github.com/HotsauceFiretruck/A-Western-Story/blob/ecf2e66496581487207b9c7d7b33f67ee0657709/src/arena/NameScene.js#L29)

**Comment by tranqnhan** [comment]
I fixed it by implementing rex text input plugin rather than making the text input as html.
